CREATE TABLE Departments (
	ID INT NOT NULL
		CONSTRAINT PK_Departments PRIMARY KEY CLUSTERED,
	Name VARCHAR(100) NOT NULL,
	City VARCHAR(20) NULL,
	Building VARCHAR(100) NULL,
	BuildingFloor INT NULL
);

CREATE TABLE Employees (
	ID INT NOT NULL
		CONSTRAINT PK_Employees PRIMARY KEY CLUSTERED,
	Name VARCHAR(100) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Sex CHAR(1) NOT NULL,
	StartDate DATE NOT NULL,
	DepartmentID INT NOT NULL
		CONSTRAINT FK_Employees_Departments FOREIGN KEY REFERENCES Departments(ID),
	LeaderID INT NULL
		CONSTRAINT FK_Employees_Employees FOREIGN KEY REFERENCES Employees(ID),
	Position VARCHAR(50) NULL,
	Education VARCHAR(50) NULL,
	CardNumber VARCHAR(20) NULL
);

CREATE TABLE Salaries (
	ID INT NOT NULL
		CONSTRAINT PK_Salaries PRIMARY KEY CLUSTERED,
	Amount MONEY NOT NULL,
	EmployeeID INT NOT NULL
		CONSTRAINT FK_Salaries_Employees FOREIGN KEY REFERENCES Employees(ID),
	PaymentDate DATE NOT NULL
);

CREATE TABLE Bonuses (
	ID INT NOT NULL
		CONSTRAINT PK_Bonuses PRIMARY KEY CLUSTERED,
	Amount MONEY NOT NULL,
	EmployeeID INT NOT NULL
		CONSTRAINT FK_Bonuses_Employees FOREIGN KEY REFERENCES Employees(ID),
	PaymentDate DATE NOT NULL,
	Category VARCHAR(50) NULL 
);

CREATE TABLE Penalties (
	ID INT NOT NULL
		CONSTRAINT PK_Penalties PRIMARY KEY CLUSTERED,
	Amount MONEY NOT NULL,
	EmployeeID INT NOT NULL
		CONSTRAINT FK_Penalties_Employees FOREIGN KEY REFERENCES Employees(ID),
	PenaltyDate DATE NOT NULL, 
	PaymentDate DATE NULL,
	Category VARCHAR(50) NULL,
	SeverityCategory VARCHAR(50) NULL
);
